repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: ['-c', '.yamllint.yaml']

  - repo: local
    hooks:
      - id: validate-schema
        name: Validate config schema
        entry: npx --yes ajv-cli validate -s templates/config.schema.json -d templates/config.yaml
        language: system
        files: ^templates/(config\.yaml|config\.schema\.json)$
        pass_filenames: false

      - id: markdownlint
        name: Markdown Lint
        entry: npx --yes markdownlint-cli2
        language: system
        types: [markdown]
